export const ROUTES = {
	LANDING: '/',
	LOGIN: '/login',
	HOME: '/home',
	HOME_ISOLATION: '/home-isolation',
	TICKET: '/ticket',
	TICKET_ILLNESSES: '/ticket/illnesses',
	TICKET_SYMPTOM: '/ticket/symptom',
	TICKET_ADD: '/ticket/add',
	TICKET_VACCINE: '/ticket/vaccine',
	TICKET_REQUEST_LOCATION: '/ticket/request-location',
	TICKET_HOSPITAL: 'ticket/hospital',
	HEALTHCARE: '/healthcare',
	HEALTHCARE_INVITE: '/healthcare/invite',
	HEALTHCARE_REGISTER: '/healthcare/register',
	HEALTHCARE_CODE: '/healthcare/code',
	HEALTHCARE_QUEUE: '/healthcare/queue',
	HEALTHCARE_QUEUE_HISTORY: '/healthcare/queue/history',
	HEALTHCARE_STAFF: '/healthcare/staff',
	TERMS_AND_CONDITION: '/terms-and-conditions',
	PRIVACY_POLICY: '/privacy-policy'
};

export const PROTECTED_ROUTES = [
	ROUTES.HOME,
	ROUTES.TICKET,
	ROUTES.TICKET_ILLNESSES,
	ROUTES.TICKET_SYMPTOM,
	ROUTES.TICKET_ADD,
	ROUTES.TICKET_VACCINE,
	ROUTES.TICKET_REQUEST_LOCATION,
	ROUTES.TICKET_HOSPITAL,
	ROUTES.HEALTHCARE_CODE,
	ROUTES.HEALTHCARE_QUEUE,
	ROUTES.HEALTHCARE_QUEUE_HISTORY,
	ROUTES.HEALTHCARE_STAFF
];

export const TICKET_FLOW = [
	ROUTES.TICKET_ILLNESSES,
	ROUTES.TICKET_SYMPTOM,
	ROUTES.TICKET_ADD,
	ROUTES.TICKET_VACCINE,
	ROUTES.TICKET_REQUEST_LOCATION,
	ROUTES.TERMS_AND_CONDITION,
	ROUTES.PRIVACY_POLICY
];

const GENERAL_ROUTES = [ROUTES.TERMS_AND_CONDITION, ROUTES.PRIVACY_POLICY, ROUTES.HOME_ISOLATION];

export const HEALTHCARE_CODE_ROUTES = [ROUTES.HEALTHCARE_CODE, ...GENERAL_ROUTES];
export const HEALTHCARE_QUEUE_ROUTES = [
	ROUTES.HEALTHCARE_QUEUE,
	ROUTES.HEALTHCARE_QUEUE_HISTORY,
	...GENERAL_ROUTES
];
export const HEALTHCARE_STAFF_ROUTES = [ROUTES.HEALTHCARE_STAFF, ...GENERAL_ROUTES];
export const REPORTER_ROUTES = [ROUTES.HOME, ROUTES.TICKET, ...GENERAL_ROUTES];
